[package]
name = "core"
version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
thiserror = { workspace = true }
semver = { workspace = true }
cosmwasm-schema = { workspace = true }
serde-json-wasm = { workspace = true }
cw-utils = { workspace = true }
cw20 = { workspace = true }
